image: Visual Studio 2017

configuration:
  - Debug
  - Release

# platform:
#   - x86
#   - x64

cache:
  - appveyor\Debug
  - appveyor\Release
  - appveyor\x64

artifacts:
  - path: x64\$(configuration)\
    name: dist
    type: zip